[package]
name = "rust_htmx_app"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-files = "0.6.6"
actix-web = "4.8.0"
serde = { version = "1.0.204", features = ["derive"] }
tera = "1.20.0"
reqwest = { version = "0.11", features = ["json"] }
serde_json = "1.0"